---
- name: Deploy Portainer Agent (Windows - Standalone)
  hosts: standalone-windows
  become: true
  roles:
    - role: portainer_agent
      vars:
        portainer_agent_mode: standalone
        portainer_agent_os: wcs
