---
- name: Deploy Portainer Agent (Linux - Kubernetes) with lb
  hosts: k8s
  become: true
  roles:
    - role: grulicht.portainer_agent
      vars:
        portainer_agent_mode: k8s
        portainer_agent_os: linux
        portainer_agent_k8s_mode: lb
