---
- name: Deploy Portainer Agent (Linux - Standalone)
  hosts: standalone-linux
  become: true
  roles:
    - role: grulicht.portainer_agent
      vars:
        portainer_agent_mode: standalone
        portainer_agent_os: linux
