---
- name: Deploy Portainer Agent (Linux - Swarm)
  hosts: swarm-linux
  become: true
  roles:
    - role: grulicht.portainer_agent
      vars:
        portainer_agent_mode: swarm
        portainer_agent_os: linux
