---
- name: Deploy Portainer Agent (Linux - Podman)
  hosts: podman
  become: true
  roles:
    - role: portainer_agent
      vars:
        portainer_agent_mode: podman
        portainer_agent_os: podman
