---
- name: Create compose directory (non-edge)
  ansible.builtin.file:
    path: "{{ portainer_agent_compose_dir }}"
    state: directory
    mode: '0755'
  when: not portainer_edge_agent | default(false) | bool

- name: Create compose and data directory (edge agent)
  ansible.builtin.file:
    path: "{{ portainer_agent_compose_dir }}/data"
    state: directory
    mode: '0755'
    recurse: true
  when: portainer_edge_agent | default(false) | bool

- name: Template Portainer Edge Agent docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose-{{ portainer_agent_mode }}-edge.yml.j2"
    dest: "{{ portainer_agent_compose_dir }}/docker-compose.yml"
    mode: '0755'
  when: portainer_agent_edge | default(false) | bool

- name: Template Portainer Agent docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose-{{ portainer_agent_mode }}.yml.j2"
    dest: "{{ portainer_agent_compose_dir }}/docker-compose.yml"
    mode: '0755'
  when: not portainer_agent_edge | default(false) | bool

- name: Create volume path for Portainer agent
  ansible.builtin.file:
    path: >-
      {{
        (portainer_agent_mode in ['standalone', 'swarm'] and portainer_agent_docker_volume_path != '/var/lib/docker/volumes')
          | ternary(portainer_agent_docker_volume_path,
            (portainer_agent_mode == 'podman' and portainer_agent_podman_volume_path != '/var/lib/containers/storage/volumes')
              | ternary(portainer_agent_podman_volume_path, omit))
      }}
    state: directory
    mode: '0755'
  when: >
    (portainer_agent_mode in ['standalone', 'swarm'] and portainer_agent_docker_volume_path != '/var/lib/docker/volumes') or
    (portainer_agent_mode == 'podman' and portainer_agent_podman_volume_path != '/var/lib/containers/storage/volumes')
