FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

ENV ANSIBLE_LIBRARY=/usr/share/ansible/plugins/modules
ENV SYSTEM_CORE_PATH=/home/ansible-deploy/system-core
ENV ANSIBLE_DEPLOY_PATH=/home/ansible-deploy
ENV REGISTRY_PATH=${SYSTEM_CORE_PATH}/registry
ENV INVENTORY_PATH=${SYSTEM_CORE_PATH}/inventory

ENV VIRTUAL_ENV=/opt/ansible-venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

WORKDIR ${ANSIBLE_DEPLOY_PATH}

RUN apt-get update -y && \
    apt-get install -y \
        expect \
        git \
        libffi-dev \
        libssl-dev \
        openssh-client \
        procps \
        pycodestyle \
        python3 \
        python3-boto3 \
        python3-cffi \
        python3-dev \
        python3-dnspython \
        python3-netaddr \
        python3-pip \
        python3-venv \
        python3-pycodestyle \
        rsync \
        bash \
        yamllint && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

RUN python3 -m venv $VIRTUAL_ENV && \
    $VIRTUAL_ENV/bin/pip install --upgrade pip && \
    $VIRTUAL_ENV/bin/pip install \
        boto==2.49.0 \
        "ansible-core>=2.10,<2.15" \
        "ansible-lint>=5.4,<7.0" \
        ansible-merge-vars==5.0.0

RUN $VIRTUAL_ENV/bin/pip install --ignore-installed PyYAML==6 && \
    $VIRTUAL_ENV/bin/ansible-galaxy collection install community.aws

    RUN apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /var/lib/log/* /tmp/* /var/tmp/* /root/.ansible

CMD ["bin/bash"]
