---
- name: Converge
  hosts: all
  vars:
    portainer_agent_mode: "standalone"  # standalone / swarm / podman / k8s
    portainer_agent_os: "linux"         # linux / wsl / wcs / podman

  roles:
    - role: portainer_agent
